require(plotly)||install.packages("plotly")
library(plotly)
require(dplyr)||install.packages("dplyr")
library(dplyr)
require(shinythemes)||install.packages("shinythemes")
library(shinythemes)
require(factoextra)||install.packages("factoextra")
library(factoextra)
require(cluster)||install.packages("cluster")
library(cluster)
require(readxl)||install.packages("readxl")
library(readxl)
require(ClustOfVar)||install.packages("ClustOfVar")
library(ClustOfVar)
require(PerformanceAnalytics)||install.packages("PerformanceAnalytics")
library(PerformanceAnalytics)
require(dendextend)||install.packages("dendextend")
library(dendextend)
require(fpc)||install.packages("fpc")
library(fpc)
require(kernlab)||install.packages("kernlab")
library(kernlab)
require(mvtnorm)||install.packages("mvtnorm")
library(mvtnorm)
require(robustbase)||install.packages("robustbase")
library(robustbase)

#Introduction
source("intro.R")
#Expenditure
source("expenditure.R")
#Nutrition
source("nutrition.R")
#Access
source("accessibility.R")
source("buy-access.R")
# K means / Predictive Clustering
source("kmeans.R")

